name: ci
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  eslint-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
      - name: CI, Linter and Build
        run: |
          npm ci --legacy-peer-deps
          npm run lint
          npm run build
